version: '3'
services:
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - service-networks

  worker_1:
    build:
      context: ./redisv1
      dockerfile: rtsptestDockerfile
    image: danlee01633060/rtsptest:v1
    restart: always
    environment:
      - WORKER_ID=1
    depends_on:
      - redis
    volumes:
      - ./redisv1:/app
      - ./rtsp_test/frames/:/app/frames
    # command: sleep 100000
    networks:
      - service-networks

  worker_2:
    build:
      context: ./redisv1
      dockerfile: rtsptestDockerfile
    image: danlee01633060/rtsptest:v1
    restart: always
    environment:
      - WORKER_ID=2
    depends_on:
      - redis
    volumes:
      - ./redisv1:/app
      - ./rtsp_test/frames/:/app/frames
    # command: sleep 100000
    networks:
      - service-networks

  worker_3:
    build:
      context: ./redisv1
      dockerfile: rtsptestDockerfile
    image: danlee01633060/rtsptest:v1
    restart: always
    environment:
      - WORKER_ID=3
    depends_on:
      - redis
    volumes:
      - ./redisv1:/app
      - ./rtsp_test/frames/:/app/frames
    networks:
      - service-networks

  worker_4:
    build:
      context: ./redisv1
      dockerfile: rtsptestDockerfile
    image: danlee01633060/rtsptest:v1
    restart: always
    environment:
      - WORKER_ID=4
    depends_on:
      - redis
    volumes:
      - ./redisv1:/app
      - ./rtsp_test/frames/:/app/frames
    networks:
      - service-networks

  worker_5:
    build:
      context: ./redisv1
      dockerfile: rtsptestDockerfile
    image: danlee01633060/rtsptest:v1
    restart: always
    environment:
      - WORKER_ID=5
    depends_on:
      - redis
    volumes:
      - ./redisv1:/app
      - ./rtsp_test/frames/:/app/frames
    networks:
      - service-networks

  worker_6:
    build:
      context: ./redisv1
      dockerfile: rtsptestDockerfile
    image: danlee01633060/rtsptest:v1
    restart: always
    environment:
      - WORKER_ID=6
    depends_on:
      - redis
    volumes:
      - ./redisv1:/app
      - ./rtsp_test/frames/:/app/frames
    networks:
      - service-networks

  worker_7:
    build:
      context: ./redisv1
      dockerfile: rtsptestDockerfile
    image: danlee01633060/rtsptest:v1
    restart: always
    environment:
      - WORKER_ID=7
    depends_on:
      - redis
    volumes:
      - ./redisv1:/app
      - ./rtsp_test/frames/:/app/frames
    networks:
      - service-networks

  worker_8:
    build:
      context: ./redisv1
      dockerfile: rtsptestDockerfile
    image: danlee01633060/rtsptest:v1
    restart: always
    environment:
      - WORKER_ID=8
    depends_on:
      - redis
    volumes:
      - ./redisv1:/app
      - ./rtsp_test/frames/:/app/frames
    networks:
      - service-networks

  worker_9:
    build:
      context: ./redisv1
      dockerfile: rtsptestDockerfile
    image: danlee01633060/rtsptest:v1
    restart: always
    environment:
      - WORKER_ID=9
    depends_on:
      - redis
    volumes:
      - ./redisv1:/app
      - ./rtsp_test/frames/:/app/frames
    networks:
      - service-networks

  worker_10:
    build:
      context: ./redisv1
      dockerfile: rtsptestDockerfile
    image: danlee01633060/rtsptest:v1
    restart: always
    environment:
      - WORKER_ID=10
    depends_on:
      - redis
    volumes:
      - ./redisv1:/app
      - ./rtsp_test/frames/:/app/frames
    networks:
      - service-networks

networks:
  service-networks:
    driver: bridge
